AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.11
    Architectures:
      - x86_64
    

Parameters:
  ServiceFunctionName:
    Type: String
  LambdaFunctionPath:
    Type: String
  DLQARN:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - production
      - development

Resources:
  PlatformInitialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref ServiceFunctionName
      CodeUri: !Ref LambdaFunctionPath
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environmetn
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref DLQARN
    LogGroupName:
      Ref: PlatformInitialFunctionLogGroup
  
  PlatformInitialFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ServiceFunctionName}"
      RetentionInDays: 14
      Policies:
        - AWSLambdaExecutionRole