Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.11
    Architectures:
      - x86_64
    Environment:
      Variables:
        STAGE: Development

Parameters:
  ServiceFunctionName:
    Type: String
  LambdaFunctionPath:
    Type: String
  DLQARN:
    Type: String

Resources:
  PlatformInitialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref ServiceFunctionName
      CodeUri: !Ref LambdaFunctionPath
    DeadLetterQueue:
      Type: SNS
      TargetArn: !Ref DLQARN
  
  PlatformInitialLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ServiceFunctionName}"
      RetentionInDays: 14