AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.10
    Architectures:
      - x86_64
    

Parameters:
  ServiceFunctionName:
    Type: String
  # DLQARN:
  #   Type: String
  Environment:
    Type: String
    AllowedValues:
      - production
      - development

Resources:
  # lamdba function resource definition
  PlatformInitialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-${ServiceFunctionName}"
      CodeUri: ../lambdas/initial_deployment
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  # cloudwatch log group resource definition
  PlatformInitialFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ServiceFunctionName}"
      RetentionInDays: 14