AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.10
    Architectures:
      - x86_64
    

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - production
      - development

Resources:
  # lamdba function resource definition
  PlatformInitialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-initial-function"
      CodeUri: ../lambdas/initial_deployment
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  # cloudwatch log group resource definition
  PlatformInitialFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/initial-function"
      RetentionInDays: 14
  
  LandingBucketUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-landing-bucket-upload"
      CodeUri: ../lambdas/landing_trigger
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
    
  LandingBucketUploadLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/LandingBucketUpload"
      RetentionInDays: 14
  
  LandingBucketFuncionParam:
    Type: AWS::SSM::Parameter
    Properties:
      Value: !Ref LandingBucketUploadFunction
      Type: String
      Name: !Sub "${Environment}/services/lambdas/names/landingbucketfunction"
      
  LandingFunctionArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Value: !GetAtt LandingBucketUploadFunction.Arn
      Type: String
      Name: !Sub "${Environment}/services/lambdas/arn/landingbucketfunctionarn"
  
  LandingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-landing-queue"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt LandingDLQ
  
  SanitisedQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-sanitised-queue"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SanitisedDQL
  
  CuratedQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-curated-queue"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CuratedDLQ

  LandingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-landing-dlq"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000
    
  SanitisedDQL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "${Environment}-sanitised-dlq"
        VisibilityTimeout: 300
        MessageRetentionPeriod: 864000

  CuratedDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-curated-dlq"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000
    
  # EventBridge rules
  LandingSqsRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source: ["aws.s3"]
        detail-type: ["Object Creation"]
        detail:
          bucket:
            name: 
              - "{{resolve:ssm:/${Environment}/services/buckets/names/landingbucket}}"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt LandingQueue.Arn
          Id: "LandingQueueTarget"

  SanitisedSqsRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source: ["aws.s3"]
        detail-type: ["Object Creation"]
        detail:
          bucket:
            name: 
              - "{{resolve:ssm:/${Environment}/services/buckets/names/sanitisedbucket}}"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt SanitisedQueue.Arn
          Id: "SanitisedQueueTarget"
    
    CuratedSqsRule:
      Type: AWS::Events::Rule
      Properties:
        EventPattern:
          source: ["aws.s3"]
          detail-type: ["Object Creation"]
          detail:
            bucket:
              name: 
                - "{{resolve:ssm:/${Environment}/services/buckets/names/curatedbucket}}"
        State: "ENABLED"
        Targets:
          - Arn: !GetAtt CuratedQueue.Arn
            Id: "CuratedQueueTarget"

  # this policy will allow EventBridge to put messages in SQS
    SqsQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues: [
          !Ref LandingQueue,
          !Ref SanitisedQueue,
          !Ref CuratedQueue
        ]
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: {Service: "events.amazonaws.com"}
              Action: "sqs:SendMessage"
              Resource: !GetAtt LandingQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !GetAtt LandingSqsRule.Arn
            - Effect: Allow
              Principal: {Service: "events.amazonaws.com"}
              Action: "sqs:SendMessage"
              Resource: !GetAtt SanitisedQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !GetAtt SanitisedSqsRule.Arn
            - Effect: Allow
              Principal: {Service: "events.amazonaws.com"}
              Action: "sqs:SendMessage"
              Resource: !GetAtt CuratedQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !GetAtt CuratedSqsRule.Arn
