AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.10
    Architectures:
      - x86_64
    

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - production
      - development

Resources:
  # lamdba function resource definition
  PlatformInitialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-initial-function"
      CodeUri: ../lambdas/initial_deployment
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  # cloudwatch log group resource definition
  PlatformInitialFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/initial-function"
      RetentionInDays: 14
  
  LandingBucketUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-landing-bucket-upload"
      CodeUri: ../lambdas/landing_trigger
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
    
  LandingBucketUploadLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub "/aws/lambda/LandingBucketUpload"
      RetentionInDays: 14
    
Outputs:

  LandingBucketFunctionName:
    Value: !Ref LandingBucketUploadFunction
    Export:
      Name: !Sub "${Environment}-landing-bucket-function-name"

  LandingBucketFunctionArn:
    Value: !GetAtt LandingBucketUploadFunction.Arn
    Export:
      Name: !Sub "${Environment}-landing-bucket-function-arn"  
    
  LandingBucketUploadLogGroupName:
    Value: !Ref LandingBucketUploadLogGroup
    Export:
      Name: !Sub "${Environment}-landing-bucket-upload-log-group-name"
    
  LandingBucketUploadLogGroupArn:
    Value: !GetAtt LandingBucketUploadLogGroup.Arn
    Export:
      Name: !Sub "${Environment}-landing-bucket-upload-log-group-arn"
