AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.10
    Architectures:
      - x86_64
    

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - production
      - development

Resources:
  # lamdba function resource definition
  PlatformInitialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-initial-function"
      CodeUri: ../lambdas/initial_deployment
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  # cloudwatch log group resource definition
  PlatformInitialFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/initial-function"
      RetentionInDays: 14
  
  LandingBucketUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-landing-bucket-upload"
      CodeUri: ../lambdas/landing_trigger
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
    
  LandingBucketUploadLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/LandingBucketUpload"
      RetentionInDays: 14
    
  # EventBridge rules
  LandingSqsRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source: ["aws.s3"]
        detail-type: ["Object Creation"]
        detail:
          bucket:
            name: 
              - "{{resolve:ssm:/${Environment}/services/buckets/names/landingbucket}}"
      State: "ENABLED"
      Targets:
       - Arn:
          Fn::ImportValue:
            Fn::Sub: ${Environment}-LandingQueueName"

  # this policy will allow EventBridge to put messages in SQS
    SqsQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues: [
          !ImportValue LandingQueueName,
          !ImportValue SanitisedQueueName,
          !ImportValue CuratedQueueName
        ]
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: {Service: "events.amazonaws.com"}
              Action: "sqs:SendMessage"
              Resource: !ImportValue "${Environment}-LandingQueueArn"
              Condition:
                ArnEquals:
                  aws:SourceArn: !GetAtt LandingSqsRule.Arn
            - Effect: Allow
              Principal: {Service: "events.amazonaws.com"}
              Action: "sqs:SendMessage"
              Resource: !ImportValue "${Environment}-SanitisedQueueArn"
              Condition:
                ArnEquals:
                  aws:SourceArn: !GetAtt SanitisedSqsRule.Arn
            - Effect: Allow
              Principal: {Service: "events.amazonaws.com"}
              Action: "sqs:SendMessage"
              Resource: !ImportValue "${Environment}-CuratedQueueArn"
              Condition:
                ArnEquals:
                  aws:SourceArn: !GetAtt CuratedSqsRule.Arn

Outputs:
  LandingBucketFunctionName:
    Value: !Ref LandingBucketUploadFunction
    Export:
      Name: !Sub "${Environment}-LandingBucketFunctionName"

  LandingBucketFunctionArn:
    Value: !GetAtt LandingBucketUploadFunction.Arn
    Export:
      Name: !Sub "${Environment}-LandingBucketFunctionArn"  