AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    AllowedValues: 
      - development
      - production

Resources:
    LandingBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
          BucketName: !Sub "${Environment}-landing-bucket"
          VersioningConfiguration:
            Status: Enabled
      
    SanitisedBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
          BucketName: !Sub "${Environment}-sanitised-bucket"
          VersioningConfiguration:
            Status: Enabled

    CuratedBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
          BucketName: !Sub "${Environment}-curated-bucket"
          VersioningConfiguration:
            Status: Enabled
    
    FileTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        TableName: !Sub "${Environment}-file-table"
        AttributeDefinitions:
          - AttributeName: "BucketName"
            AttributeType: "S"
          - AttributeName: "FileName"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "BucketName"
            KeyType: "HASH"
          - AttributeName: "FileName"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true

Outputs:
  LandingBucketName:
    Value: !Ref LandingBucket
    Export:
      Name: !Sub "${Environment}-landing-bucket"
  SanitisedBucketName:
    Value: !Ref SanitisedBucket
    Export:
      Name: !Sub "${Environment}-sanitised-bucket"
  CuratedBucket:
    Value: !Ref CuratedBucket
    Export:
      Name: !Sub "${Environment}-curated-bucket"
  FileTableName:
    Value: !Ref FileTable
    Export:
      Name: !Sub "${Environment}-file-table"