AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    AllowedValues: 
      - development
      - production

Resources:
  LandingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${Environment}-landing-bucket"
      VersioningConfiguration:
        Status: Enabled

  SanitisedBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${Environment}-sanitised-bucket"
      VersioningConfiguration:
        Status: Enabled
            
  CuratedBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${Environment}-curated-bucket"
      VersioningConfiguration:
        Status: Enabled
    
  FileTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "${Environment}-file-table"
      AttributeDefinitions:
        - AttributeName: "BucketName"
          AttributeType: "S"
        - AttributeName: "FileName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "BucketName"
          KeyType: "HASH"
        - AttributeName: "FileName"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
  
  LandingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-landing-queue"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "LandingDLQ"
            - "Arn"
        maxReceiveCount: 5
    
  LandingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-landing-dlq"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000

Outputs:
  LandingBucketName:
    Description: Output referencing the landing bucket
    Value: !Ref LandingBucket
    Export:
      Name: !Sub "${Environment}-landing-bucket-name"
  
  LandingBucketArn:
    Description: Output referencing the landing bucket's ARN identifier
    Value: !GetAtt LandingBucket.Arn
    Export:
      Name: !Sub "${Environment}-landing-bucket-arn"