AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    AllowedValues: 
      - development
      - production

Resources:
    LandingBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
          BucketName: !Sub "${Environment}-landing-bucket"
          VersioningConfiguration:
            Status: Enabled

      
    SanitisedBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
          BucketName: !Sub "${Environment}-sanitised-bucket"
          VersioningConfiguration:
            Status: Enabled
            
    CuratedBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
          BucketName: !Sub "${Environment}-curated-bucket"
          VersioningConfiguration:
            Status: Enabled
    
    FileTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        TableName: !Sub "${Environment}-file-table"
        AttributeDefinitions:
          - AttributeName: "BucketName"
            AttributeType: "S"
          - AttributeName: "FileName"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "BucketName"
            KeyType: "HASH"
          - AttributeName: "FileName"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
    
    LandingBucketParam:
      Type: AWS::SSM::Parameter
      Properties:
        Value: !Ref LandingBucket
        Type: String
        Name: !Sub "${Environment}/services/buckets/names/landingbucket"
      
    LandingBucketArnParam:
      Type: AWS::SSM::Parameter
      Properties:
        Value: !GetAtt LandingBucket.Arn
        Type: String
        Name: !Sub "${Environment}/services/buckets/arn/landingbucketarn"
    
    CuratedBucketParam:
      Type: AWS::SSM::Parameter
      Properties:
        Value: !Ref CuratedBucket
        Type: String
        Name: !Sub "${Environment}/services/buckets/names/curatedbucket"
      
    CuratedBucketArnParam:
      Type: AWS::SSM::Parameter
      Properties:
        Value: !GetAtt CuratedBucket.Arn
        Type: String
        Name: !Sub "${Environment}/services/buckets/arn/curatedbucketarn"
    
    SanitisedBucketParam:
      Type: AWS::SSM::Parameter
      Properties:
        Value: !Ref SanitisedBucket
        Type: String
        Name: !Sub "${Environment}/services/buckets/names/sanitisedbucket"
      
    SanitisedBucketArnParam:
      Type: AWS::SSM::Parameter
      Properties:
        Value: !GetAtt SanitisedBucket.Arn
        Type: String
        Name: !Sub "${Environment}/services/buckets/arn/sanitisedbucketarn"
    
