AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  LandingBucketName:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - production
      - development

Resources:
    LandingBucket:
      Type: AWS::S3::Bucket
      Properties:
          BucketName: !Sub "${Environment}-landing-bucket"
          VersioningConfiguration:
            Status: Enabled
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
    
    FileTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: !Sub "${Environment}-file-table"
        AttributeDefinitions:
          - AttributeName: "BucketName"
            AttributeType: "S"
          - AttributeName: "FileName"
            AttributeType: "S"
          - AttributeName: "Sanitised"
            AttributeType: "S"
          - AttributeName: "Curated"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "BucketName"
            KeyType: "HASH"
          - AttributeName: "FileName"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEENABLED: true
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain

Outputs:
  LandingBucketName:
    Value: !Ref LandingBucket
    Export:
      Name: !Sub "${Environment}-landing-bucket"
  FileTableName:
    Value: !Ref FileTable
    Export:
      Name: !Sub ${Environment}-file-table"