AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    AllowedValues: 
      - development
      - production

Resources:
  LandingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${Environment}-landing-bucket"
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  SanitisedBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${Environment}-sanitised-bucket"
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
            
  CuratedBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${Environment}-curated-bucket"
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
    
  FileTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "${Environment}-file-table"
      AttributeDefinitions:
        - AttributeName: "BucketName"
          AttributeType: "S"
        - AttributeName: "FileName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "BucketName"
          KeyType: "HASH"
        - AttributeName: "FileName"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
  
  LandingQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      QueueName: !Sub "${Environment}-landing-queue"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "LandingDLQ"
            - "Arn"
        maxReceiveCount: 5
    
  LandingDLQ:
    Type: AWS::SQS::Queue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      QueueName: !Sub "${Environment}-landing-dlq"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000
  
  SanitisedQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      QueueName: !Sub "${Environment}-sanitised-queue"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "SanitisedDLQ"
            - "Arn"
        maxReceiveCount: 5
  
  SanitisedDLQ:
    Type: AWS::SQS::Queue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      QueueName: !Sub "${Environment}-santised-dlq"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000
  
  CuratedQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      QueueName: !Sub "${Environment}-curated-queue"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "CuratedDLQ"
            - "Arn"
        maxReceiveCount: 5
  
  CuratedDLQ:
    Type: AWS::SQS::Queue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      QueueName: !Sub "${Environment}-curated-dlq"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 864000
  
  # This is the policy attached to the SQS queue that allows the event brige to put messages in the queue
  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref LandingQueue
        - !Ref SanitisedQueue
        - !Ref CuratedQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource:
              - !GetAtt LandingQueue.Arn
              - !GetAtt SanitisedQueue.Arn
              - !GetAtt CuratedQueue.Arn
Outputs:
  LandingBucketName:
    Description: Output referencing the landing bucket
    Value: !Ref LandingBucket
    Export:
      Name: !Sub "${Environment}-landing-bucket-name"
  
  LandingBucketArn:
    Description: Output referencing the landing bucket's ARN identifier
    Value: !GetAtt LandingBucket.Arn
    Export:
      Name: !Sub "${Environment}-landing-bucket-arn"
  
  SanitisedBucketName:
    Description: Output referencing the sanitised bucket
    Value: !Ref SanitisedBucket
    Export:
      Name: !Sub "${Environment}-sanitised-bucket-name"

  SanitisedBucketArn:
    Description: Output referencing the sanitised bucket arn
    Value: !GetAtt SanitisedBucket.Arn
    Export:
      Name: !Sub "${Environment}-sanitised-bucket-arn"
  
  CuratedBucketName:
    Description: Ouptut referencing the curated bucket
    Value: !Ref CuratedBucket
    Export:
      Name: !Sub "${Environment}-curated-bucket-name"
  
  CuratedBucketArn:
    Description: Output referencing the curated bucket arn
    Value: !GetAtt CuratedBucket.Arn
    Export:
      Name: !Sub "${Environment}-curated-bucket-arn"
  FileTableName:
    Description: Output referencing the dynamodb table 'FileTable'
    Value: !Ref FileTable
    Export:
      Name: !Sub "${Environment}-file-table-name"

  FileTableArn:
    Description: Output referencing the dynamodb table arn
    Value: !GetAtt FileTable.Arn
    Export:
      Name: !Sub "${Environment}-file-table-arn"
  
  LandingQueueName:
    Description: Output referening the sqs landing queue for landing files
    Value: !Ref LandingQueue
    Export:
      Name: !Sub "${Environment}-landing-queue-name"

  LandingQueueArn:
    Description: Output referencing the arn of the sqs queue for landing files
    Value: !GetAtt LandingQueue.Arn
    Export: 
      Name: !Sub "${Environment}-landing-queue-arn"
  
  LandingDLQName:
    Description: Output referencing the dead letter queue for landing files
    Value: !Ref LandingDLQ
    Export:
      Name: !Sub "${Environment}-landing-dl-queue-name"

  LandingDLQArn:
    Description: Output referencing the arn of the dead letter queue for landing files
    Value: !GetAtt LandingDLQ.Arn
    Export:
      Name: !Sub "${Environment}-landing-dl-queue-arn"
  
  SanitisedQueueName:
    Description: Output referencing the SQS queue for files landing in the sanitised bucket
    Value: !Ref SanitisedQueue
    Export:
      Name: !Sub "${Environment}-sanitised-queue-name"

  SanitisedQueueArn:
    Description: Output referencing the sanitised sqs queue arn
    Value: !GetAtt SanitisedQueue.Arn
    Export:
      Name: !Sub "${Environment}-sanitised-queue-arn"
  
  SanitisedDLQName:
    Description: Output referencing the dead letter queue for sanitised files
    Value: !Ref SanitisedDLQ
    Export:
      Name: !Sub "${Environment}-sanitised-dl-queue-name"
  
  SanitisedDLQArn:
    Description: Output referencing the arn of the dead letter queue for the sanitised files
    Value: !GetAtt SanitisedDLQ.Arn
    Export:
      Name: !Sub "${Environment}-sanitised-dl-queue-arn"
      
  CuratedQueueName:
    Description: Output referencing the SQS queue for files landing in the curated bucket
    Value: !Ref CuratedQueue
    Export:
      Name: !Sub "${Environment}-curated-queue-name"

  CuratedQueueArn:
    Description: Output referencing the ARN of the SQS queue for files landing in the curate bucket
    Value: !GetAtt CuratedQueue.Arn
    Export:
      Name: !Sub "${Environment}-curated-queue-arn"

  CuratedDLQName:
    Description: Output referencing the DLQ for the sqs curated queue
    Value: !Ref CuratedDLQ
    Export:
      Name: !Sub "${Environment}-curated-dl-queue-name"

  CuratedDLQArn:
    Description: Output referencing the ARN of the DLQ for the sqs curated queue
    Value: !GetAtt CuratedDLQ.Arn
    Export:
      Name: !Sub "${Environment}-curated-dl-queue-arn"
